Whole AI Rework
PlatWalker/game-jbzd pull request #32
Opened 2021-01-06 01:10 UTC by kumdzio

2021-01-07 16:35 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/DoomerController.cs
> +            Move(false, 0.0f, MainCharacterTransform.position);
poproszę o zmianę na MoveTo(); oraz dodanie summary

2021-01-07 16:37 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/DoomerController.cs
> +                    if (jumpDirection == new Vector3(0.0f,0.0f,0.0f))
new Vecotr3(0,0,0) można zamienić na Vector3.zero

2021-01-07 16:39 UTC, PlatWalker requested changes
małe poprawki, ale ogólnie gites

2021-01-07 16:39 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/DoomerController.cs
> +                Move(false, 1f, SpawnPoint);
zamienić 1f na zmienną prywatną

2021-01-07 16:39 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Gowniak/GowniakController.cs
> +    private Stopwatch _aggroTimer;
czemu jest tuaj podłoga na początku nazwy ?

2021-01-10 13:20 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/AISwitcher.cs
> +    Renderer mesh;
Te zmienne powinny mieć `private` przed nazwami.

2021-01-10 13:21 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/AISwitcher.cs
> +                    if(enemyController!= null) enemyController.SwitchAI();
Herezja!

2021-01-10 13:22 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/AISwitcher.cs
> +                    if(enemyController!= null) enemyController.SwitchAI();
Herezja!

2021-01-10 13:22 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/AISwitcher.cs
> +                    if(enemyController!= null) enemyController.SwitchAI();
Herezja!

2021-01-10 13:24 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/AggroController.cs
> +        if (animator.GetCurrentAnimatorStateInfo(0).normalizedTime > 0.99 && animator.GetCurrentAnimatorStateInfo(0).IsName("Armature|Aggro"))
`ArmatureAggro` łatwiej napisać niż `Armature|Aggro`

2021-01-10 13:24 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Doomer/DoomerController.cs
> +    private bool hasDoneSpecialAttack;
Zobacz jakie ładne!

2021-01-10 13:35 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/EnemyController.cs
> +                                transform.position.z);
Herezja!

2021-01-10 13:43 UTC, Sharashino reviewed
Bardzo ładne skrypty, pare tylko poprawek

2021-01-11 20:32 UTC, PlatWalker approved these changes

2021-01-11 20:33 UTC, merged