Rpg core creator
PlatWalker/game-jbzd pull request #34
Opened 2021-01-13 18:22 UTC by Sharashino

Add form RPG Core:
- Items
- Stats
- Actions
- Inventory
- Stat Creator
- Experience
- Leveling

2021-01-14 09:57 UTC, PlatWalker requested changes
w zasadzie 90 % to prośba o używanie property xd

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/Actions/ItemPickup.cs
> +    [SerializeField] public Item item;
Public nie musi być serializowane bo jest serializowane samo w sobie to po pierwsze. Po drugie public nie używamy w C#. Zamiast niego property powinno być. Po trzecie czy to na pewno powinno być publiczne? Może prywatne powinno być?

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/Item.cs
> +    public StatCreator xd;
zamienić na property i zmienić nazwę bo "xd" to nie jest dobra nazwa lel

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/Item.cs
> +    public bool canPickUp;
To wszystko powinno być property jeśli ma być publiczne.

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/CharacterStats.cs
> +        public int toNextLevel;
to powinno być property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/CharacterStats.cs
> +        #endregion
dem znowu java'owe abominacje, zamienić na property poproszę.

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/Stat.cs
> +        public string statName;
property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/Stat.cs
> +        public List<int> modifiers = new List<int>();
property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/Stat.cs
> +        public int SetBaseValue(int value)
najbardziej klasyczny przykład property, nawet zmienna domyślna przekazywania wartości w setterze w property nazywa się value.

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Base/Stat.cs
> +        public int GetBaseValue()
property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Player/PlayerStats.cs
> +            }
wjebałbyś to do funkcji jakiejś, która nazywa się "Testing" czy coś takiego. Byłoby ładniej.

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Stats/Player/PlayerStats.cs
> +        [HideInInspector] public List<Stat> modifiableStatsList = new List<Stat>();
property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/UI/PlayerUI/StatBox.cs
> +        public StatCreator statCreator;
property

2021-01-14 09:57 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/UI/PlayerUI/StatBox.cs
> +        public void SetStatValue(int value)
klasyka property

2021-01-14 21:38 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/Item.cs
> +    public bool canPickUp;
Nie bo to scriptable object

2021-01-15 09:48 UTC, PlatWalker approved these changes

2021-01-15 09:49 UTC, merged