Core dialogue creator
PlatWalker/game-jbzd pull request #39
Opened 2021-02-21 21:08 UTC by Sharashino

Add Dialogue Editor and Dialogue Actions & Reaction Basics

2021-02-23 14:19 UTC, Sharashino commented
Dawaj tom recenzje śmieciu

2021-02-24 10:26 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/LoadCSV.cs
> +        private string csvFileName = "DialogueCSV_Load.csv";
tego chyba nie chcesz modyfikować? To może być readonly.

2021-02-24 11:27 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/LoadCSV.cs
> +        private void LoadInToNode(List<List<string>> _result, List<string> _headers, DialogueNodeData _nodeData)
Nie robiliśmy ale w niektórych przypadkach chciałem mieć takie same nazwy w funkcji i żeby zamiast this pisać po prostu `_nazwaZmiennej`

2021-02-24 11:30 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/LoadCSV.cs
> +        private string csvFileName = "DialogueCSV_Load.csv";
Racja, powinno być readonly.

2021-02-24 11:33 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/LoadCSV.cs
> +            var isBlank = new Regex(@"\s");
Nie dotykałem tego kodu jeszcze. Jest komentarz że nie ja go pisałem

2021-02-24 11:34 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/SaveCSV.cs
> +        private string csvSeparator = ",";
Yes

2021-02-24 11:35 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/CSV Tool/SaveCSV.cs
> +        private string idName = "Guid ID";
Lista nie może być readonly ale reszta tak

2021-02-24 11:38 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/DialogueSaveAndLoad.cs
> +        public DialogueSaveAndLoad(DialogueGraphView _graphView)
Cały plik poprawiony

2021-02-24 11:40 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/Nodes/DialogueNode.cs
> +        }
Ponieważ czasem tworzę obiekt `DialogueNode` , który jest pusty i nie ma w sobie żadnych wartości. Np przy ładowaniu albo zapisywaniu. Dlatego są dwa konstruktory. Jeden przeciążony a drugi nie

2021-02-24 11:40 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/Nodes/EventNode.cs
> +        }
Ponieważ czasem tworzę obiekt `EventNode`, który jest pusty i nie ma w sobie żadnych wartości. Np przy ładowaniu albo zapisywaniu. Dlatego są dwa konstruktory. Jeden przeciążony a drugi nie

2021-02-24 11:40 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/Nodes/StatCheckNode.cs
> +        }
Ponieważ czasem tworzę obiekt `StatCheckNode`, który jest pusty i nie ma w sobie żadnych wartości. Np przy ładowaniu albo zapisywaniu. Dlatego są dwa konstruktory. Jeden przeciążony a drugi nie

2021-02-24 11:41 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Runtime/Scriptable Objects/DialogueContainerSO.cs
> +            }
*ignored*

2021-02-24 11:41 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Runtime/Scriptable Objects/DialogueContainerSO.cs
> +    }
Ponieważ czasem tworzę obiekt `StartNodeData`, , który jest pusty i nie ma w sobie żadnych wartości. Np przy ładowaniu albo zapisywaniu. Dlatego są dwa konstruktory. Jeden przeciążony a drugi nie

2021-02-24 11:43 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Runtime/Scriptable Objects/DialogueEventSO.cs
> +        }
Niestety jest to SO, które używane jest do tworzenia eventów w dialogach. Z racji tego, że nie wiedziałem jakie są eventy, zrobiłem tak, że dziedzicząc z tego obiektu i dodając do niego dowolne pola będziemy mogli odpalić ten event w dialogu. Funkcja `RunEvent()` wykonuje event z obiektu w dialogu.

2021-02-24 11:46 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Runtime/enums/DialogueFaceImageType.cs
> +}
Przy używaniu namespace, stworzenie space'u `Enums` jest genialne. Z feedbacku z firmy INTERMARUM wiem, że fajnie jest jeśli taki namespace istnieje. Kiedy korzystasz z enumów to raczej w wielu skryptach na raz. Więc lepiej mieć to w osobnym pliku i odpowiednim namespace. Wtedy nie odwołujesz się do klasy w której jest enum tylko do namespace'u i masz każdy enum z gry.

2021-02-24 11:47 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Use/DialogueController.cs
> +            };
Kiedy masz `UnityAction` w tym przypadku o nazwie statCheck. Przypisujesz akcję do klikniętego buttona `()` i jak klikniesz `=>` wykona się `Debug.Log("Chujowe staty");`

2021-02-24 11:48 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/TextMesh Pro/Fonts/LiberationSans - OFL.txt
> +THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRIN
Nie powinniśmy. To Asset, w pełni darmowy, a to jego licencja. Przy budowaniu gry w plikach tego nie będzie.

2021-02-24 11:59 UTC, PlatWalker requested changes
Ogarnij te podłogi REEEEEEE

2021-02-24 12:21 UTC, PlatWalker approved these changes
gites

2021-02-24 12:56 UTC, merged