AI with StateMachines and NavMesh
PlatWalker/game-jbzd pull request #58
Opened 2021-03-28 20:11 UTC by kumdzio

Only two months of works so i think that you will be able to check this until tommorow

2021-04-06 20:00 UTC, Sharashino commented
I have nice beka with the comment you wrote @kumdzio

2021-04-07 12:16 UTC, PlatWalker requested changes

2021-04-07 12:16 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/MainHero/Movement variation 2/PlayerController.cs
> +        }
CO TO JEST ?! czemu mi się wtrążalasz w nieswoje sprawy, a dokładniej moje sprawy? Co to jest proszę o wyjaśnienia xd

2021-04-07 17:17 UTC, kumdzio commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Gowniak/GowniakController.cs
> +        HandleLogicPerformaceBoost();
zwróciłem uwagę przed PR na to że metoda HandleLogicPerformanceBoost  jest wywoływana w każdym przeciwniku i myślałem czy nie wrzucić jej do klasy bazowej jednak jak to zrobiłem to dotarło do mnie że zmiana taka to wrzucenie dodatkowej linijki do klasy bazowej i konieczność zamiany jednej linii w każdej klasie pochodnej na jedną linię o innej treści. No i później też pomyślałem, że może jakiś inny przeciwnik nie będzie z tego korzystał bo nie będzie potrzeby albo będzie potrzeba by z tego nie korzystać i tak doszedłem do wniosku, że nie ma sensu zwiększać objętości kodu skoro prawie niczego to nie zmienia.
NO ALE
nie wiem jak powinno być to zrobione "poprawnie" więc jeśli moje przemyślenia są błędne to napisz to poprawię to gówno

2021-04-07 17:18 UTC, kumdzio commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Gowniak/GowniakController.cs
> +    private static bool aggroCommenced=false;
wiem, że nie lubimy ale w tym wypadku to chyba najefektowniejszy sposób. Aggro ma się wykonywać tylko raz przy pierwszym spotkaniu danego typu przeciwnika. Inny sposób który jest łatwy i przychodzi mi do głowy to jakaś tablica w game managerze

2021-04-07 17:19 UTC, kumdzio commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Monkey/ProjectilesLimiter.cs
>      private static long nextID = 0;
Nie, zaraz to przerobię na bez staticową wersję z czasem zamiast ilością bananów

2021-04-07 17:20 UTC, kumdzio commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Monkey/ProjectilesLimiter.cs
> +    private int projectilesLimit=50;
zaraz zmienię cały skrypt na niszczenie po czasie

2021-04-07 17:20 UTC, kumdzio commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/MainHero/Movement variation 2/PlayerController.cs
> +        }
Przempraszam :_(

2021-04-07 17:23 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Gowniak/GowniakController.cs
> +        HandleLogicPerformaceBoost();
to jebać jest gites

2021-04-07 17:25 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Enemies Scripts/Gowniak/GowniakController.cs
> +    private static bool aggroCommenced=false;
No to jak uważasz, że musi zostać to niech zostanie. Ja tam nie będę aż tak głęboko wchodził  w kod xd Ale jednak może spróbuj coś poszperać w internecie może tam jest jakieś proste rozwiązanie do tego.

2021-04-11 14:52 UTC, Sharashino commented
Zauważyłem błąd w twoich skryptach, dzisiaj (11.04) go pokażę na spotkaniu, ale póki co wrzucam labelke bug :)

2021-04-18 12:04 UTC, kumdzio commented
@PlatWalker Dodałem namespace oraz przełączanie AI przed startem gry.
Teraz już chyba możesz mergować to.

2021-04-18 12:37 UTC, PlatWalker approved these changes

2021-04-18 12:37 UTC, merged