Dialogue-Inventory Addition
PlatWalker/game-jbzd pull request #64
Opened 2021-05-01 20:53 UTC by Sharashino

Created new node - ItemCheckNode which lets you check player's inventory for item in dialogues
Added ability to give player an item as a dialogue result

2021-05-07 09:54 UTC, PlatWalker requested changes

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/Nodes/ItemCheckNode.cs
> +        }
to ma być takie puste?

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Use/DialogueController.cs
> +                    }
wut nigga? Z tego co widzę to ten if w ogóle potrzebny jest? Tak czy inaczej zostanie zwrócone "false" xd

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Use/DialogueTalk.cs
> +            //Debug.Log(nodeData.StatCheckType + " | " + nodeData.StatCheckValue);
Z tego co kiedyś dał feedback ziomek chyba nie powinniśmy zostawiać zakomentowanego kodu przy pushowaniu na tech-demo?

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Inventory/Editor/InventoryWizard.cs
> +        void OnGUI()
strasznie nieczytelne to jest. Może udałoby ci się rozbić na kilka funkcji/metody/klas ?

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Inventory/Editor/InventoryWizard.cs
> +                    CleanUp(); CleanUp(); CleanUp(); CleanUp();
4 razy ? xd

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Inventory/PickupItem.cs
> +/// Testowa klasa do podnoszenia itemów na klik myszy i ogólnie do wyjebania jest
skoro do wyjebania to czemu nadal jest? xd

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/Actions/ItemConsume.cs
> +    //}
nie zostawiamy dużo zakomentowanego kodu przypominam.

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/ConsumableItem1.cs
> +    //}
nie zostawiamy zkaomentowanego kodu

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/Item.cs
> +           // Inventory.instance.RemoveItem(this);
nie zostawiamy zakomentowanego kodu

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +        //private Inventory inventory;
nie zostawiamy zakomentowanego kodu

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +           // inventory = Inventory.instance;
nie zostawiamy zakomentowanego kodu

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +                //inventory.AddItem(oldItem);
nie zostawiamy zakomentowanego kodu

2021-05-07 09:54 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +                //inventory.AddItem(oldItem);
nie zostawiamy zakomentowanego kodu

2021-05-07 10:17 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Use/DialogueController.cs
> +                    }
Tak, gdyż ten case czeka na fix Inventory, który pozwoli sprawdzać czy mamy dany item, póki co zostawiłem żeby zwracało false w celu weryfikacji poprawności działania.

2021-05-07 10:19 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Editor/Editor/Nodes/ItemCheckNode.cs
> +        }
Tak musi być puste ponieważ przy tworzeniu noda (w dosłownie pierwszej milisekundzie) z item check nie dajemy mu żadnego itemu ani nie precyzujemy checka, stąd pustka bo inaczej by wywalało błąd przy tworzeniu noda

2021-05-07 10:19 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Dialogues/Dialogue Use/DialogueTalk.cs
> +            //Debug.Log(nodeData.StatCheckType + " | " + nodeData.StatCheckValue);
Do wyjebania, zapomniałem

2021-05-07 14:57 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Inventory/Editor/InventoryWizard.cs
> +                    CleanUp(); CleanUp(); CleanUp(); CleanUp();
4 razy ze względu na utworzenie 4 podobiektów w trakcie spawnowania faktycznego inventory. Obiekty te są usuwane ale ich właściwości są przenoszone na finalny obiekt inventory

2021-05-07 15:01 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/ItemBase/Item.cs
> +           // Inventory.instance.RemoveItem(this);
Stary kod. Do wyjebania

2021-05-07 15:01 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +           // inventory = Inventory.instance;
Stary kod. Do wyjebania

2021-05-07 15:01 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +                //inventory.AddItem(oldItem);
Stary kod. Do wyjebania

2021-05-07 15:01 UTC, Sharashino commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Managers/EquipmentManager.cs
> +                //inventory.AddItem(oldItem);
Stary kod. Do wyjebania

2021-05-10 10:10 UTC, PlatWalker approved these changes

2021-05-10 10:13 UTC, PlatWalker commented on Pieklo dzidowca kregi spierdolenia/Assets/Scripts/Items/Actions/ItemConsume.cs
> +    //}
Bump

2021-05-12 17:01 UTC, PlatWalker approved these changes

2021-05-12 17:02 UTC, merged

2021-05-12 17:22 UTC, Sharashino commented
Dzięki za merge pozdrawiam